language: none
deploy:
  provider: s3
  access_key_id: AKIAINYINDPKGDJ3HJAQ
  secret_access_key:
    secure: WfMNre/Y2VMvzaso6lMRBzX8gaNuyLnWGGV46aW1Vv8bkm9v5tH1pfDo+DfqlzPAvpD+08dIadUfiCMfadNuQmAppChnBVo2pkdsOTIY9W3xWPnleISYPJtIHJDM/a2l3PbXFyhthitMoN/ZOsNoUPs8cfY1uspXXgssfZUYATnlV7rwfZ4L+XhVkUnhwsFJPQO/P0rUrTHXBo9NA2TA3QgPFAZgf23gXTaFH1Ba5wr4T7hIy28m6zyZ9Uy2h6LKHjSNg29gNaiKDuVLncQMb+9t3l9x5HMyKWpq/vsQGsGKE+yy5maySTKmU7eRPy1G3sXM+fz+y2J8ajBMl5hHLOdHg72/QamSNU6PgSorOIHzMQvOMSBqAeKCqh80k2k8l0a+YaR8uSyE5MhsqxqJ2rF7Nxi0bjEAEUYV7IYgGQBqSdzfbOaSlFyI74Ml0VN3USFf3UiK6RPpALAPHYWWvCKu5fMmqljUGf6Pyhc+26zedJmw4d0/D7SG139B0JRYf+G9fppvoo1hEcG5yb0ljdnPB7Eg6Oqa0UcY+S7c6OqgzFwiFJ6tjmAmIUUNur3cuFVY48w+AQzNgek82gFJyhOJ3ZeFMr/7B+vpf7s6r+9J1cbUBp0S9q9rGRgdo31l1WAYgq6nLylBx4LgpTqb277LWnK22whDVehrFj6qygU=
  bucket: bryankyle.me
  acl: ''
  on:
    repo: bkyle/bryankyle.me
